config/routes.rb
Greencode::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  post '/office_admin' => 'office_admin/dashboard#index', :as => :office_admin_root

  root :to => 'pages#home'

  devise_for :users,
             :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" },
             :skip => [ :password, :registration ]

  match '/delayed_job' => DelayedJobWeb, :anchor => false

  get '/gracias' => 'pages#gracias'
  get '/fbshared' => 'pages#fbshared'
  get '/fbshared2' => 'pages#fbshared2'
  get '/fbshared3' => 'pages#fbshared3'
  match 'sitemap.xml.gz', :controller => 'sitemap', :action => 'index'

    match '/como-funciona' => 'pages#how_it_works', :as => :how_it_works_pages

    match '/eco-amigable' => 'pages#projects', :as => :ecoamigable_pages
    match '/retailers' => 'pages#customers', :as => :customers_pages
    match '/retailers_beneficios' => 'pages#customers2', :as => :customers2_pages
    match '/terminos-y-condiciones' => 'pages#tos', :as => :tos_pages
    match '/politicas-de-privacidad' => 'pages#politica', :as => :politica_pages
    match '/terminos-y-condiciones-concurso' => 'pages#concurso', :as => :tycc_pages
    match '/concurso2014' => 'pages#concurso2014', :as => :tycc2014_pages

    match '/contacto' => 'contacts#create', :via => :post , :as => :contacts

    match '/mis-marcas-favoritas' => 'favorites#index', :via => :get , :as => :favorites
    match '/selecciona-tus-marcas-favoritas' => 'favorites#index', :via => :get , :as => :favorites_first_time
    match '/confirma-tus-datos' => 'settings#edit', :via => :get , :as => :first_time
    match '/mi-marca-favorita/:brand_id/actualizar' => 'favorites#add', :via => :put , :as => ''
    match '/compartir-en-facebook'  => 'favorites#facebook_wall', :via => :post, :as => ''

    match '/bonos-recibidos' => 'gift_codes#index_angular', :via => :get, :as => :gift_codes
    match '/bonos-enviados' => 'gift_codes#index_sent_angular', :via => :get, :as => :gift_codes_sent
    match '/bono/:view_id/token/:token' => 'gift_codes#show', :via => :get, :as => :gift_code
    match '/bono/crear' => 'gift_codes#create', :via => :post, :as => :gift_code_create
    match '/bono/:ref_sale' => 'gift_codes#download', :via => :get, :as => :gift_code_download
    match '/bono/:ref_sale/view' => 'gift_codes#view', :via => :get, :as => :gift_code_view

    match '/perfil' => 'settings#edit', :via => :get, :as => :edit_settings
    match '/perfil' => 'settings#update', :via => :put, :as => :settings
    match '/perfil/validar_correo/:token' => 'settings#validate_account', :via => :get, :as => :validate_account_settings
    match '/confirmation_email' => 'settings#confirmation_email', :via => :put
    match '/confirmation_birthday' => 'settings#confirmation_birthday', :via => :put
    match '/confirmation_city' => 'settings#confirmation_city', :via => :put

    match '/regalar-bono' => 'give#index_brands_angular', :via => :get, :as => :give
    match '/regalar-bono-amigo' => 'give#index_friends_angular', :via => :get, :as => :friend_give

=begin
    match '/puntos' => 'points#index', :via => :get, :as => :points
    match '/puntos/giftcode/:ref_sale' => 'points#gift_code', :via => :get, :as => :gift_codes_points
    match '/services/points/campaigns' => 'points#json_campaigns_points', :via => :get, :as => :services_points
    match '/services/points/campaigns/:campaign_id/gift_codes/create' => 'points#create_gift_code', :via => :post, :as => :services_points_create_gift_code
=end

=begin
    match '/amigos' => 'friends#index_angular', :via => :get, :as => :friends
    match '/invitar-amigo/:fbk_user_id' => 'friends#invite', :via => :post, :as => :invite_friend
    match '/perfil/amigo/:user_id' => 'friends#profile', :via => :get, :as => :profile_friend
    match '/amigos/referidos' => 'friends#referrals', :via => :get, :as => :services_friends_referrals
    match '/amigos/invitados' => 'friends#guests', :via => :get, :as => :services_friends_guests
    match '/amigos/por-invitar' => 'friends#for_inviting', :via => :get, :as => :services_friends_for_inviting
    match '/amigos/en-giftcode' => 'friends#in_gift_code', :via => :get, :as => :services_friends_in_gift_code
=end

    match '/json/amigos' => 'json#friends', :via => :get, :as => :friends_json
    match '/json/referidos-amigos' => 'json#referrals_friends', :via => :get, :as => :referrals_friends_json
    match '/amigos/referidos' => 'friends#referrals', :via => :get, :as => :services_friends_referrals
    match '/json/parametros-marca-giftcode' => 'json#brand_parameters_gift_code',  :via => :post, :as => :brand_parameters_gift_code_json
    match '/json/marcas' => 'json#brands',  :via => :get, :as => :brands_json
    match '/json/marcas-favoritas-amigo-regalar' => 'json#brands_favorites_friend_give',  :via => :post, :as => :brands_favorites_friend_give_json
    match '/json/marcas-favoritas' => 'json#favorites',  :via => :get, :as => :brand_favorites_json
    match '/json/marcas-favoritas-amigo/:friend_id' => 'json#favorites_friend',  :via => :get, :as => :brand_favorites_friend_json
    match '/json/marcas-favoritas-amigos' => 'json#friends_favorite_brands',  :via => :get, :as => :friends_favorite_brands_json
    match '/json/marca-favoritas-amigos/:brand_id' => 'json#friends_favorite_brand',  :via => :get, :as => :friends_favorite_brand_json
    match '/json/invite-amigos' => 'json#invite_friends', :via => :get, :as => :invite_friend_json
    match '/json/gift_code' => 'json#gift_code', :via => :post, :as => :gift_code_json
    match '/json/gift_code_sent' => 'json#gift_code_sent', :via => :post, :as => :gift_code_sent_json
    match '/json/gift_codes' => 'json#gift_codes', :via => :get, :as => :gift_codes_json
    match '/json/gift_codes_sent' => 'json#gift_codes_sent', :via => :get, :as => :gift_codes_sent_json
    match '/json/date_time_server' => 'json#get_date_time_server', :via => :get, :as => :get_date_time_server_json

    match '/payments/:ref_sale' => 'payments#index', :via => :get, :as => :payments
    match '/payments/:ref_sale' => 'payments#index', :via => :put, :as => :payments
    match '/payments/confirmation/:ref_sale' => 'payments#confirmation', :via => :get, :as => :confirmation_payments
    match '/payments/demo/:ref_sale' => 'payments#demo', :via => :get, :as => :demo_payments

  match '/favorites/suggest' => 'favorites#suggest', :via => :post

  match '/redemption' => 'third_party#redemption', :via => :post
  match '/reverse_redemption' => 'third_party#reverse_redemption', :via => :post
  match '/pending_redemption' => 'third_party#pending_redemption', :via => :post
  match '/confirm_redemption' => 'third_party#confirm_redemption', :via => :post
  match '/get_balance' => 'third_party#get_balance', :via => :post
  match '/embebed_giftcode' => 'third_party#embebed_giftcode', :via => :get, :as => :embebed_giftcode
  match '/embebed_giftcode_create' => 'third_party#embebed_giftcode_create', :via => :post, :as => :embebed_giftcode_create
  match '/embebed_giftcode_confirmation' => 'third_party#embebed_giftcode_confirmation', :via => :get, :as => :embebed_giftcode_create
  match '/get_payments' => 'third_party#get_brand_payments', :via => :post

  get '/bonos_gratuitos' => 'gift_code_free#index'

  get '/nosotros' => 'pages#team'
  get '/landing_2' => 'pages#landing2'
  get '/landing_3' => 'pages#landing_3'
  get '/landing_4' => 'pages#landing_4'
  match '/:brand_name' => 'landing_page#index', :via => :get, :as => :landing_page

  use_doorkeeper

  namespace :api do
    namespace :v1 do
      resource  :settings do
        collection do
          get :profile
          put :update_image
          put :update_birthday
          put :update
          get :birthday_confirmation
        end
      end
      resources :categories, :only => [:index]
      resources :friends, :only => [:index, :friends_in_gift_code]
      resource :brands, :only => [] do
        collection do
          get :all
          get 'friends_favorite_brand/:brand_id', to: :friends_favorite_brand
          get :favorite_brands
        end
      end
      resource :gift_codes, :only => [] do
        collection do
          get :sent
          get :received
          get 'received/:ref_sale', to: :gift_code_received
          post :create
          get 'parameters_brand/:brand_id', to: :parameters_brand
        end
      end
      resource :favorites, :only => [] do
        collection do
          post :add
        end
      end

    end
  end

  namespace :api do
    namespace :off do
      namespace :v1 do
        resources :pages,  :only => [:index] do
          collection do
            get :':brand_name', to: :index
          end
        end
        resources :brands, :only => [:index, :show]
        resources :gift_codes, :only => [:create]
      end
    end
  end

end

app/controllers/api/off/v1/gift_codes_controller.rb
class Api::Off::V1::GiftCodesController < Api::Off::V1::ApplicationController

  respond_to :json

  def create
    @gift_code = GiftCode.new

    @gift_code.send_notifications_now = params['send_notifications_now']
    @gift_code.send_date_time = params['send_date_time']
    @gift_code.from_first_name = params['from_first_name']
    @gift_code.from_last_name = params['from_last_name']
    @gift_code.from_email = params['from_email']
    @gift_code.to_first_name = params['to_first_name']
    @gift_code.to_last_name = params['to_last_name']
    @gift_code.to_mobile_phone = params['to_mobile_phone']
    @gift_code.to_email = params['to_email']
    @gift_code.gift_card_id = params['gift_card_id']
    @gift_code.to_country = 'CO'
    @gift_code.body_message = params['body_message']
    @gift_code.to_address = params['to_address']
    @gift_code.to_state = params['to_state']
    @gift_code.to_city = params['to_city']


    from_user = User.find_by_email ( @gift_code.from_email )
    if from_user.nil?
      from_user = User.user_new( @gift_code.from_first_name, @gift_code.from_last_name, @gift_code.from_email )
      puts from_user.errors.messages
    end
    to_user = User.find_by_email( @gift_code.to_email )
    if to_user.nil?
      to_user = User.user_new( @gift_code.to_first_name, @gift_code.to_last_name, @gift_code.to_email )
      puts to_user.errors.messages
    end

    @gift_code.from_user = from_user
    @gift_code.to_user = to_user
    @gift_code = load_data( @gift_code )
    @gift_code.gift_code_state_id = GiftCodeState::STATES[:generated_and_payment_pending]

    campaign = @gift_code.gift_card.campaign
    brand_codes = campaign.brand_codes.find_by_active_for_payment true

    if brand_codes
      @entity = brand_codes.third_party_entity
    else
      @entity = nil
    end

    @gift_code.save

    respond_with @gift_code

  end

  private

    def load_data( gift_code = nil )
      unless gift_code.gift_card_id.nil?
        gift_code.gift_card = GiftCard.find gift_code.gift_card_id
        gift_code.cost = gift_code.gift_card.cost
        if gift_code.send_notifications_now
          gift_code.send_date_time = Time.zone.now
        end
        gift_code.valid_for_days = gift_code.gift_card.valid_for_days
        gift_code.iva = gift_code.gift_card.campaign.iva
        gift_code.calculate_base_iva
        gift_code.generate_ref_sale
      end
      return gift_code
    end

end

app/controllers/api/v1/gift_codes_controller.rb
class Api::V1::GiftCodesController < Api::V1::BaseController
  include ActionView::Helpers::NumberHelper
  doorkeeper_for :all

  def sent
    gift_codes =  current_user.gift_codes_sent
    data  = gift_codes.collect {
        |gc| {
          :ref_sale => gc.ref_sale,
          :cost => number_to_currency(gc.cost, :separator => ",", :delimiter => ".", :precision => 0, :locale => :en),
          :redeemed => gc.redeemed_state.as_json,
          :to_name => gc.complete_to_name,
          :body_message => gc.body_message,
          :img_url => (
          if gc.is_a_free_gift_code?
            gc.office.brand.image.url(:thumb195).to_s
          else
            if gc.type == "PUNTOS"
              gc.campaign_point.brand.image.url(:thumb195).to_s
            else
              gc.gift_card.campaign.brand.image.url(:thumb195).to_s
            end
          end
          )
      }
    }
    render :json => data.as_json
  end

  def received
    gift_codes =  current_user.gift_codes_received
    data  = gift_codes.collect {
        |gc| {
          :ref_sale => gc.ref_sale,
          :cost => number_to_currency(gc.cost, :separator => ",", :delimiter => ".", :precision => 0, :locale => :en),
          :redeemed => gc.redeemed_state.as_json,
          :body_message => gc.body_message,
          :available_balance =>  number_to_currency(gc.available_balance, :separator => ",", :delimiter => ".", :precision => 0, :locale => :en),
          :from_name => (
          if gc.is_a_free_gift_code?
            gc.office.brand.name
          else
            gc.from_first_name + ' ' + gc.from_last_name
          end
          ),
          :img_url => (
          if gc.is_a_free_gift_code?
            gc.office.brand.image.url(:thumb195).to_s
          else
            if gc.type == "PUNTOS"
              gc.campaign_point.brand.image.url(:thumb195).to_s
            else
              gc.gift_card.campaign.brand.image.url(:thumb195).to_s
            end
          end
          )
      }
    }
    render :json => data.as_json
  end

  def gift_code_received
    gift_code =  current_user.gift_codes_received.find_by_ref_sale( params[:ref_sale] )
    if !gift_code.nil?
      if gift_code.is_a_free_gift_code?
        brand = gift_code.free_campaign.office.brand
        country = ''
        office = gift_code.free_campaign.office
      else
        brand = gift_code.gift_card.campaign.brand
        country = gift_code.gift_card.campaign.country.name
        office = ''
      end
      render :json => {
          :data => gift_code.as_json(:only => [:from_first_name, :from_last_name, :to_first_name, :to_last_name, :body_message]),
          :is_free => gift_code.is_a_free_gift_code?,
          :cost =>  number_to_currency(gift_code.cost, :separator => ",", :delimiter => ".", :precision => 0, :locale => :en),
          :available_balance =>  number_to_currency(gift_code.available_balance, :separator => ",", :delimiter => ".", :precision => 0, :locale => :en),
          :qr => ChunkyPNG::Image.from_blob(gift_code.binary_qr_code_image).to_data_url,
          :pin => gift_code.redemption_pin_formatted(' '),
          # :city =>  gift_code.to_city.name,
          :country => country,
          :office => office.as_json(:only => [:office_name,]),
          :valid => l( gift_code.valid_until, :format => :web),
          :brand => brand.as_json(:only => [:image, :name ])
      }
    else
      render :json => {}
    end
  end

  def create
    if params[:gift_code]
      data = params[:gift_code]
    else
      data = params
    end
    gift_code = GiftCode.new(data)
    msg = { :type => 'error', :text => 'Error al crear bono' }
    json = { flash: msg }.as_json
    if !gift_code.nil?
      gift_code.from_user = current_user
      gift_code.from_first_name = current_user.first_name
      gift_code.from_last_name = current_user.last_name
      gift_code.from_email = current_user.email
      gift_code.gift_code_state_id = GiftCodeState::STATES[:generated_and_payment_pending]
      gift_code.cost = gift_code.gift_card.cost
      gift_code.iva = gift_code.gift_card.campaign.iva
      if gift_code.send_notifications_now
        gift_code.send_date_time = Time.zone.now
      end
      gift_code.valid_for_days = gift_code.gift_card.valid_for_days
      gift_code.calculate_base_iva
      gift_code.generate_ref_sale
      # fb_id = gift_code.to_email.split("@")[0].to_i
      # to_user = User.find_by_fbk_user_id( fb_id )
      to_user = User.find_by_email( gift_code.to_email )
      if to_user.nil?
        to_user = User::user_new( gift_code.to_first_name,gift_code.to_last_name,gift_code.to_email )
      else
        gift_code.to_email = to_user.email
      end
      gift_code.to_user = to_user
      if gift_code.save
        msg = { :type => 'success', :text => 'Se guardo bono' }
      else
        msg = { :type => 'error', :text => 'Error al guardar bono', :errors => gift_code.errors.to_json }
        puts "ERROR AL CREAR GIFTCODE"
      end
      puts msg
      json = {
          flash: msg,
          ref_sale: gift_code.ref_sale,
          # city: gift_code.to_city.name,
          cost_current: gift_code.gift_card.cost_current,
          currency_short_name: gift_code.gift_card.campaign.currency.short_name
      }.as_json
    end
    render :json => json
  end

  def parameters_brand
    brand = Brand.find params[:brand_id]
    json = Array.new
    if brand
      country =  country()
      campaign = brand.campaign_enable_for_selling
      cities = campaign.cities
      gift_cards = campaign.gift_cards_enable_for_selling
      json = {
          :cities => cities.as_json(:only => [:id, :name]),
          :gift_cards => gift_cards.as_json(
              :only => [:id ],
              :methods => [:cost_current, :cost_plus_cost_total_admin_current ],
              :include => { :campaign => {
                  :include => {
                      :currency => { :only => [ :short_name ] }
                  },
                  :only => ""
              }
              }
          ),
          :cost => {
              :admin => { :value => campaign.cost_total_admin_current, :currency => { :short_name => campaign.currency.short_name } }.as_json
          }.as_json,
          :url => brand.image.as_json
      }
    end
    render :json => json.as_json
  end


end

app/views/gift_codes/_light_banner.html.erb
<div class="graybanner no-padding no-margin">
  <div class="row" >
    <div class="large-12 columns"  >
      <h4 class="subheader text-center">Recibir bonos electrónicos de regalo es muy sencillo.</h4>
      <h6 class="subheader text-center">Dale a conocer a tus amigos tus marcas favoritas para que recibas lo que realmente quieres</h6>
      <br>
      <div class="centered">
        <a href="<%= favorites_path %>" class="button pre radius greenbg2">Seleccionar Marcas Favoritas</a>
      </div>
      <br>
    </div>
  </div>
</div>

app/views/gift_codes/_menu.html.erb
<div class="row">
  <div class="text-center">
    <div class="sub-menu">
      <ul class="inline-list">
        <li class="<%= 'active' if action_name == 'index_angular' && controller_name == 'gift_codes' %>"><%= link_to 'Bonos Recibidos', gift_codes_path %></li>
        <li class="<%= 'active' if action_name == 'index_sent_angular' && controller_name == 'gift_codes' %>"><%= link_to 'Bonos Enviados', gift_codes_sent_path %></li>
      </ul>
    </div>
  </div>
</div>

app/views/gift_codes/_modal_show.html.erb
<div id="friend-id" class="reveal-modal medium no-reveal-margin" data-options="closeOnBackgroundClick:false">
  <div class="row">
    <div class="large-10 columns large-centered">
      <div class="bono bigone modal">
        <div class="row collapse">
          <div class="large-4-static columns">
            <img ng-src="{{_gift_code.brand.image.thumb180.url}}" class="brand-ico" width="180" height="181" alt="">
          </div>
          <div class="large-8-static columns">
            <div class="whos">
              <h4><span class="greentxt">De: </span> {{
                {
                true: ( _gift_code.brand.name | characters:40 ),
                false: ( ( _gift_code.data.from_first_name + ' ' + _gift_code.data.from_last_name ) | characters:40 )
                }
                [_gift_code.is_free]
                }}
              </h4>
              <h4><span class="greentxt">Para: </span> {{((_gift_code.data.to_first_name + ' ' + _gift_code.data.to_last_name) | characters:35)}}</h4>
              <h4><span class="greentxt">Saldo: </span>{{(_gift_code.available_balance)}}</h4>
              <h2 ng-bind="_gift_code.cost"></h2>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="large-10 columns large-centered">
            <div class="giftnote">
              <p class="in-modal" ng-bind="_gift_code.data.body_message" ></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <a class="close-reveal-modal"> <span>Cerrar</span> &#215;</a>
  <a class="flip-card" data-reveal-id="friend-id-back"> <span>Ver reverso</span> <%= image_tag "reverso.png" %> </a>
</div>


<div id="friend-id-back" class="reveal-modal medium no-reveal-margin" data-options="closeOnBackgroundClick:false">
  <div class="row">
      <div class="bono modal white centered">
        <div class="row">
          <div class="whos">
            <img src="/assets/icono_grande.png" class="qr" alt="" width="74" height="84" />
            <h4 class="text-center">PIN: {{ _gift_code.pin }}</h4>
            <h4 class="text-center">PIN: {{ _gift_code.card_number }}</h4>
            <h4 class="text-center">PIN: {{ _gift_code.card_key }}</h4>
            <!--<h6 class="subheader text-center">Ciudad de destino: {{_gift_code.city}}</h6> -->
            <h6 class="subheader text-center">Válido hasta: {{_gift_code.valid}}</h6>
          </div>
          <div class="large-11 column large-centered text-right no-margin no-padding">
            <a href="/bono/{{ _gift_code.ref_sale }}" class="download-icon"><span>Descargar</span> <%= image_tag "download-icon.png" %></a>
          </div>
        </div>
        <div class="greenbg">
          <div class="row">
            <div class="large-10 columns large-centered">
              <p class="legal-advice whitetxt">Con este bono electrónico, estas contribuyendo con el medio ambiente al evitar el uso de tarjetas plásticas</p>
            </div>
          </div>
        </div>
      </div>

    <p class="text-center whitetxt padding-top-20">{{
      {
      true: '' + _gift_code.brand.name + ' te acaba de enviar un (Bono de Regalo) que podr&aacute;s reclamar en la tienda '+ _gift_code.office.office_name + ' en la ciudad de ' + _gift_code.city + '.',
      false: 'El presente Giftcode (Bono virtual de regalo) es personal e intransferible, si lo compartes o lo envías a otra persona estarás cediendo el derecho adquirido. Válido únicamente hasta la fecha establecida. Canjeable únicamente en las tiendas ' + _gift_code.brand.name + ' de ' + _gift_code.country + '. Cangeable por cualquier artículo disponible en las tiendas autorizadas, no canjeable por dinero. El valor de la compra no es reembonsable'
      }
      [_gift_code.is_free]
      }}</p>

  </div>
  <a class="close-reveal-modal"> <span>Cerrar</span> &#215;</a>
  <a class="flip-card back-flip" data-reveal-id="friend-id"> <span>Volver</span> <%= image_tag "volver.png" %> </a>
</div>

app/views/gift_codes/download.html.erb
Error en cargar imagen

app/views/gift_codes/index_angular.html.erb
<%# render 'personal-banner' %>
<%# render 'menu' %>
<% if  current_user.gift_codes_received.count == 0 %>
<div class="row">
  <div class="large-12 columns">
    <div class="">
      <!--<hr>-->
      <h4 class="subheader text-center padding-top-50">Aún no has recibido tu primer giftcode</h4>
      <h4 class="subheader text-center"><i>Invita y comparte con tus amigos, recibir giftcodes de lo que te gusta es algo inolvidable.</i></h4>
      <br>
      <div class="centered">
        <%= link_to 'Invitar amigos', friend_give_path, class: 'button pre radius greenbg2' %>
      </div>
      <br>
      <br>
      <br>
    </div>
  </div>
</div>
<% else  %>
<div ng-controller="GiftCodesCtrl" ng-init="load_gift_codes_received();" >
  <div class="row">
    <div class="large-12 columns">
      <div class="">
        <h4 class="subheader text-center padding-top-20">Tienes <span class="label label-count" ><%= current_user.gift_codes_received.count %></span> bonos de regalo</h4>
      </div>
    </div>
    <hr>
  </div>
  <div class="main-ux">
    <div class="row">
      <div class="large-12 columns large-centered">
        <ul class="brands-circle text-center show-hide" ng-show="gift_codes" >
          <li class="list show-hide" ng-repeat="(index, gift_code) in gift_codes" id="gift_code_{{index + 1}}"  ng-show="gift_codes">
            <img
                ng-click="load_gift_code(gift_code.ref_sale, index + 1 )"
                ng-src="{{gift_code.img_url}}"
                alt=""
                width="180"
                style="cursor:pointer;"
            >
            <div class="friends-number" ng-show="gift_code.redeemed.code == 1 || gift_code.redeemed.code == 2 || gift_code.redeemed.code == 3">
              <h4 class="subheader whitetxt no-after" title="{{gift_code.redeemed.message}}"><span class="big-check">✔</span></h4>
            </div>
            <h5 class="subheader" ng-bind="'De: ' + ( gift_code.from_name | characters:14 )"></h5>
            <h5 class='subheader' ng-bind="gift_code.cost"></h5>
          </li>
        </ul>
        <div ng-hide="gift_codes" class="preloader"></div>
      </div>
    </div>
  </div>


  <%# GIFTCODE  %>
    <%= render 'show' %>
  <%# FIN GIFTCODE  %>


  <%# MODAL  %>
    <%# render 'modal_show' %>
  <%# FIN MODAL  %>

</div>

<% end  %>

app/views/gift_codes/index_sent_angular.html.erb
<%# render 'personal-banner' %>
<%# render 'menu' %>

<% if current_user.gift_codes_sent.count == 0 %>
<div class="row">
  <div class="large-12 columns">
    <div class="">
      <!--<hr>-->
      <h4 class="subheader text-center padding-top-50">Aún no has sorprendido a alguien con un giftcode</h4>
      <h4 class="subheader text-center"><i>recuerda que es muy sencillo.</i></h4>
      <br>
      <div class="centered">
        <%= link_to 'Regalar', give_path, class: 'button pre radius greenbg2' %>
      </div>
      <br>
      <br>
      <br>
    </div>
  </div>
</div>
<% else  %>
<div ng-controller="GiftCodesCtrl" ng-init="load_gift_codes_sent();" >
  <div class="row">
    <div class="large-12 columns">
      <div class="">
        <h4 class="subheader text-center padding-top-20">Has enviado <span class="label label-count" ><%= current_user.gift_codes_sent.count %></span> bonos de regalo</h4>
      </div>
    </div>
  </div>
  <hr>
  <div class="main-ux">
    <div class="row">
      <div class="large-12 columns">
        <ul class="brands-circle text-center show-hide" ng-show="gift_codes" >
          <li class="list show-hide" ng-repeat="(index, gift_code) in gift_codes" id="gift_code_{{index + 1}}" >
            <img
            ng-click="load_gift_code_sent(gift_code.ref_sale, index + 1 )"
            ng-src="{{gift_code.img_url}}"
            alt=""
            width="180"
            style="cursor:pointer"
            >
            <div class="friends-number" ng-show="gift_code.redeemed.code == 1 || gift_code.redeemed.code == 2 || gift_code.redeemed.code == 3">
              <h4 class="subheader whitetxt no-after" title="{{gift_code.redeemed.message}}"><span class="big-check">✔</span></h4>
            </div>
            <h5 class="subheader" ng-bind="'Para: ' + ( gift_code.to_name | characters:14 )"> </h5>
            <h5 class='subheader' ng-bind="gift_code.cost"></h5>
          </li>
        </ul>
        <div ng-hide="gift_codes" class="preloader"></div>
      </div>
    </div>
  </div>

  <%# GIFTCODE  %>
  <%= render 'show' %>
  <%# FIN GIFTCODE  %>


  <%# MODAL  %>
  <%# render 'modal_show' %>
  <%# FIN MODAL  %>

  <%= render 'light_banner' %>
</div>
<% end  %>

app/views/gift_codes/view.html.erb
<div class="row">
    <%= render 'show_version_email' %>
</div>