config/routes.rb
Greencode::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  post '/office_admin' => 'office_admin/dashboard#index', :as => :office_admin_root

  root :to => 'pages#home'

  devise_for :users,
             :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" },
             :skip => [ :password, :registration ]

  match '/delayed_job' => DelayedJobWeb, :anchor => false

  get '/gracias' => 'pages#gracias'
  get '/fbshared' => 'pages#fbshared'
  get '/fbshared2' => 'pages#fbshared2'
  get '/fbshared3' => 'pages#fbshared3'
  match 'sitemap.xml.gz', :controller => 'sitemap', :action => 'index'

    match '/como-funciona' => 'pages#how_it_works', :as => :how_it_works_pages

    match '/eco-amigable' => 'pages#projects', :as => :ecoamigable_pages
    match '/retailers' => 'pages#customers', :as => :customers_pages
    match '/retailers_beneficios' => 'pages#customers2', :as => :customers2_pages
    match '/terminos-y-condiciones' => 'pages#tos', :as => :tos_pages
    match '/politicas-de-privacidad' => 'pages#politica', :as => :politica_pages
    match '/terminos-y-condiciones-concurso' => 'pages#concurso', :as => :tycc_pages
    match '/concurso2014' => 'pages#concurso2014', :as => :tycc2014_pages

    match '/contacto' => 'contacts#create', :via => :post , :as => :contacts

    match '/mis-marcas-favoritas' => 'favorites#index', :via => :get , :as => :favorites
    match '/selecciona-tus-marcas-favoritas' => 'favorites#index', :via => :get , :as => :favorites_first_time
    match '/confirma-tus-datos' => 'settings#edit', :via => :get , :as => :first_time
    match '/mi-marca-favorita/:brand_id/actualizar' => 'favorites#add', :via => :put , :as => ''
    match '/compartir-en-facebook'  => 'favorites#facebook_wall', :via => :post, :as => ''

    match '/bonos-recibidos' => 'gift_codes#index_angular', :via => :get, :as => :gift_codes
    match '/bonos-enviados' => 'gift_codes#index_sent_angular', :via => :get, :as => :gift_codes_sent
    match '/bono/:view_id/token/:token' => 'gift_codes#show', :via => :get, :as => :gift_code
    match '/bono/crear' => 'gift_codes#create', :via => :post, :as => :gift_code_create
    match '/bono/:ref_sale' => 'gift_codes#download', :via => :get, :as => :gift_code_download
    match '/bono/:ref_sale/view' => 'gift_codes#view', :via => :get, :as => :gift_code_view

    match '/perfil' => 'settings#edit', :via => :get, :as => :edit_settings
    match '/perfil' => 'settings#update', :via => :put, :as => :settings
    match '/perfil/validar_correo/:token' => 'settings#validate_account', :via => :get, :as => :validate_account_settings
    match '/confirmation_email' => 'settings#confirmation_email', :via => :put
    match '/confirmation_birthday' => 'settings#confirmation_birthday', :via => :put
    match '/confirmation_city' => 'settings#confirmation_city', :via => :put

    match '/regalar-bono' => 'give#index_brands_angular', :via => :get, :as => :give
    match '/regalar-bono-amigo' => 'give#index_friends_angular', :via => :get, :as => :friend_give

=begin
    match '/puntos' => 'points#index', :via => :get, :as => :points
    match '/puntos/giftcode/:ref_sale' => 'points#gift_code', :via => :get, :as => :gift_codes_points
    match '/services/points/campaigns' => 'points#json_campaigns_points', :via => :get, :as => :services_points
    match '/services/points/campaigns/:campaign_id/gift_codes/create' => 'points#create_gift_code', :via => :post, :as => :services_points_create_gift_code
=end

=begin
    match '/amigos' => 'friends#index_angular', :via => :get, :as => :friends
    match '/invitar-amigo/:fbk_user_id' => 'friends#invite', :via => :post, :as => :invite_friend
    match '/perfil/amigo/:user_id' => 'friends#profile', :via => :get, :as => :profile_friend
    match '/amigos/referidos' => 'friends#referrals', :via => :get, :as => :services_friends_referrals
    match '/amigos/invitados' => 'friends#guests', :via => :get, :as => :services_friends_guests
    match '/amigos/por-invitar' => 'friends#for_inviting', :via => :get, :as => :services_friends_for_inviting
    match '/amigos/en-giftcode' => 'friends#in_gift_code', :via => :get, :as => :services_friends_in_gift_code
=end

    match '/json/amigos' => 'json#friends', :via => :get, :as => :friends_json
    match '/json/referidos-amigos' => 'json#referrals_friends', :via => :get, :as => :referrals_friends_json
    match '/amigos/referidos' => 'friends#referrals', :via => :get, :as => :services_friends_referrals
    match '/json/parametros-marca-giftcode' => 'json#brand_parameters_gift_code',  :via => :post, :as => :brand_parameters_gift_code_json
    match '/json/marcas' => 'json#brands',  :via => :get, :as => :brands_json
    match '/json/marcas-favoritas-amigo-regalar' => 'json#brands_favorites_friend_give',  :via => :post, :as => :brands_favorites_friend_give_json
    match '/json/marcas-favoritas' => 'json#favorites',  :via => :get, :as => :brand_favorites_json
    match '/json/marcas-favoritas-amigo/:friend_id' => 'json#favorites_friend',  :via => :get, :as => :brand_favorites_friend_json
    match '/json/marcas-favoritas-amigos' => 'json#friends_favorite_brands',  :via => :get, :as => :friends_favorite_brands_json
    match '/json/marca-favoritas-amigos/:brand_id' => 'json#friends_favorite_brand',  :via => :get, :as => :friends_favorite_brand_json
    match '/json/invite-amigos' => 'json#invite_friends', :via => :get, :as => :invite_friend_json
    match '/json/gift_code' => 'json#gift_code', :via => :post, :as => :gift_code_json
    match '/json/gift_code_sent' => 'json#gift_code_sent', :via => :post, :as => :gift_code_sent_json
    match '/json/gift_codes' => 'json#gift_codes', :via => :get, :as => :gift_codes_json
    match '/json/gift_codes_sent' => 'json#gift_codes_sent', :via => :get, :as => :gift_codes_sent_json
    match '/json/date_time_server' => 'json#get_date_time_server', :via => :get, :as => :get_date_time_server_json

    match '/payments/:ref_sale' => 'payments#index', :via => :get, :as => :payments
    match '/payments/:ref_sale' => 'payments#index', :via => :put, :as => :payments
    match '/payments/confirmation/:ref_sale' => 'payments#confirmation', :via => :get, :as => :confirmation_payments
    match '/payments/demo/:ref_sale' => 'payments#demo', :via => :get, :as => :demo_payments

  match '/favorites/suggest' => 'favorites#suggest', :via => :post

  match '/redemption' => 'third_party#redemption', :via => :post
  match '/reverse_redemption' => 'third_party#reverse_redemption', :via => :post
  match '/pending_redemption' => 'third_party#pending_redemption', :via => :post
  match '/confirm_redemption' => 'third_party#confirm_redemption', :via => :post
  match '/get_balance' => 'third_party#get_balance', :via => :post
  match '/embebed_giftcode' => 'third_party#embebed_giftcode', :via => :get, :as => :embebed_giftcode
  match '/embebed_giftcode_create' => 'third_party#embebed_giftcode_create', :via => :post, :as => :embebed_giftcode_create
  match '/embebed_giftcode_confirmation' => 'third_party#embebed_giftcode_confirmation', :via => :get, :as => :embebed_giftcode_create
  match '/get_payments' => 'third_party#get_brand_payments', :via => :post

  get '/bonos_gratuitos' => 'gift_code_free#index'

  get '/nosotros' => 'pages#team'
  get '/landing_2' => 'pages#landing2'
  get '/landing_3' => 'pages#landing_3'
  get '/landing_4' => 'pages#landing_4'
  match '/:brand_name' => 'landing_page#index', :via => :get, :as => :landing_page

  use_doorkeeper

  namespace :api do
    namespace :v1 do
      resource  :settings do
        collection do
          get :profile
          put :update_image
          put :update_birthday
          put :update
          get :birthday_confirmation
        end
      end
      resources :categories, :only => [:index]
      resources :friends, :only => [:index, :friends_in_gift_code]
      resource :brands, :only => [] do
        collection do
          get :all
          get 'friends_favorite_brand/:brand_id', to: :friends_favorite_brand
          get :favorite_brands
        end
      end
      resource :gift_codes, :only => [] do
        collection do
          get :sent
          get :received
          get 'received/:ref_sale', to: :gift_code_received
          post :create
          get 'parameters_brand/:brand_id', to: :parameters_brand
        end
      end
      resource :favorites, :only => [] do
        collection do
          post :add
        end
      end

    end
  end

  namespace :api do
    namespace :off do
      namespace :v1 do
        resources :pages,  :only => [:index] do
          collection do
            get :':brand_name', to: :index
          end
        end
        resources :brands, :only => [:index, :show]
        resources :gift_codes, :only => [:create]
      end
    end
  end

end

app/views/gift_code_notifier/_firma.html.erb
Att,<br>
<br>
Alex<br>
CEO & Founder<br>
<a href="http://www.giftcode.co" style="color: #858585;text-decoration: none;" target="_blank">www.giftcode.co</a>

app/views/gift_code_notifier/confirmation_email.html.erb
<%= render "head" %>
<center>
  <table align="center" border="0" cellpadding="0" cellspacing="0" height="100%" width="100%" id="bodyTable" style="border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;margin: 0;padding: 0;height: 100% !important;width: 100% !important;">
    <tbody>
    <tr>
      <td align="center" valign="top" id="bodyCell" style="mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust:100%;margin: 0;padding: 20px;border-top: 0;height: 100% !important;width: 100% !important;">
        <!-- BEGIN TEMPLATE // -->
        <table border="0" cellpadding="0" cellspacing="0" width="600" id="templateContainer" style="border-collapse: collapse;mso-table-lspace:0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;border: 0;">
          <tbody>
          <tr style="border-bottom-color: #110d0a">
            <td align="center" valign="top" style="mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">
              <!--BEGIN PREHEADER // -->
              <table border="0" cellpadding="0" cellspacing="0" width="600" id="templatePreheader" style="border-collapse:collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;background-color: #4ca036;border-top: 0;border-bottom: 0;">
                <tbody>
                <tr>
                  <td valign="top" class="preheaderContainer" style="padding-top:9px;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">
                    <table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnTextBlock" style="border-collapse: collapse;mso-table-lspace:0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">
                      <tbody class="mcnTextBlockOuter">
                      <tr>
                        <td valign="top" class="mcnTextBlockInner" style="mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">
                          <table align="left" border="0" cellpadding="0" cellspacing="0" width="600" class="mcnTextContentContainer" style="border-collapse:collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">
                            <tbody>
                            <tr>
                              <td valign="top" class="mcnTextContent" width="600" style="padding: 9px 0px 9px 0px;background-color: #4ca036;mso-table-lspace: 0pt;mso-table-rspace:0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;font-family: Helvetica;font-size: 11px;line-height: 125%;text-align:center;">
                                <img align="center" alt="" src="http://greencode.co/images/logo_email_nuevo.png" width="233" style="max-width: 233px;padding-bottom: 0;display: inline !important;vertical-align: bottom;border: 0;outline: none;text-decoration:none;-ms-interpolation-mode: bicubic;" class="mcnImage">
                              </td>
                            </tr>
                            </tbody>
                          </table>
                        </td>
                      </tr>
                      </tbody>
                    </table>
                  </td>
                </tr>
                </tbody>
              </table>
              <!-- // END PREHEADER -->
            </td>
          </tr>

          <tr style="background-color:#ffffff;">
            <td align="center" valign="top" style="mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;background-color:#ffffff;">
              <table border="0" cellpadding="0" cellspacing="0" width="100%" id="templateColumns" style="border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;border-top: 0;border-bottom: 0;background-color:#ffffff;">
                <tbody>
                <tr>
                  <td align="left" valign="top" class="columnsContainer" width="100%" style="mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">
                    <table border="0" cellpadding="0" cellspacing="0" width="100%" class="templateColumn" style="border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;width: 100%;">
                      <tbody>
                      <tr>
                        <td valign="top" class="leftColumnContainer" style="mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust:100%;">
                          <table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnCaptionBlock" style="border-collapse:collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">
                            <tbody class="mcnCaptionBlockOuter">
                            <tr>
                              <td class="mcnCaptionBlockInner" valign="top" style="padding: 9px;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">
                                <table border="0" cellpadding="0" cellspacing="0" class="mcnCaptionRightContentOuter" width="100%" style="border-collapse:collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">
                                  <tbody>
                                  <tr>
                                    <td valign="top" class="mcnCaptionRightContentInner" style="padding: 0 9px;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">
                                      <table class="mcnCaptionRightTextContentContainer" align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">
                                        <tbody>
                                        <tr>
                                          <td valign="top" class="mcnTextContent" style="mso-table-lspace:7pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #858585;font-family: Helvetica;font-size:15px;line-height: 150%;text-align: left;padding: 50px 0px;">
                                            <p style="padding: 0px 0px;text-align: left;mso-table-lspace:0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;font-family: Helvetica;font-size:15px;line-height: 150%;">
                                              Hola <%= @user.first_name %> es un placer saludarte,
                                            </p>
                                            <p style="padding: 0px 0px;text-align: left;mso-table-lspace:0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;font-family: Helvetica;font-size:15px;line-height: 150%;">
                                              Para cambiar el correo electronico debes confirmar tu cuenta a través del siguiente enlace:
                                            </p>
                                            <p>
                                                <a href="<%= validate_account_settings_url( @user.token_validate_email )%>" target="_blank" style="color: #559c43;">Has click aqui!</a>
                                            </p>
                                            <%= render 'firma' %>
                                          </td>
                                        </tr>
                                        </tbody>
                                      </table>
                                    </td>
                                  </tr>
                                  </tbody>
                                </table>
                              </td>
                            </tr>
                            </tbody>
                          </table>
                        </td>
                      </tr>
                      </tbody>
                    </table>
                  </td>
                </tr>
                </tbody>
              </table>
            </td>
          </tr>

          <%= render 'footer_gift_code' %>

          </tbody>
        </table>
        <!-- // END TEMPLATE-->
      </td>
    </tr>
    </tbody>
  </table>
</center>
<%= render "footer" %>

app/views/gift_code_notifier/contact_message.html.erb
Mensaje enviado desde la página de contacto de giftcode.co
<br/>
Email: <%= @contact.email %><br/>
Mensaje <%= @contact.message %><br/>

app/views/gift_code_notifier/friends.html.erb
<%= render "head" %>
<center>
<table align="center" border="0" cellpadding="0" cellspacing="0" height="100%" width="100%" id="bodyTable" style="border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;margin: 0;padding: 0;height: 100% !important;width: 100% !important;">
<tbody>
<tr>
<td align="center" valign="top" id="bodyCell" style="mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust:100%;margin: 0;padding: 20px;border-top: 0;height: 100% !important;width: 100% !important;">
<!-- BEGIN TEMPLATE // -->
<table border="0" cellpadding="0" cellspacing="0" width="600" id="templateContainer" style="border-collapse: collapse;mso-table-lspace:0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;border: 0;">
<tbody>
<tr style="border-bottom-color: #110d0a">
  <td align="center" valign="top" style="mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">
    <!--BEGIN PREHEADER // -->
    <table border="0" cellpadding="0" cellspacing="0" width="600" id="templatePreheader" style="border-collapse:collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;background-color: #4ca036;border-top: 0;border-bottom: 0;">
      <tbody>
      <tr>
        <td valign="top" class="preheaderContainer" style="padding-top:9px;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">
          <table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnTextBlock" style="border-collapse: collapse;mso-table-lspace:0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">
            <tbody class="mcnTextBlockOuter">
            <tr>
              <td valign="top" class="mcnTextBlockInner" style="mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">
                <table align="left" border="0" cellpadding="0" cellspacing="0" width="600" class="mcnTextContentContainer" style="border-collapse:collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">
                  <tbody>
                  <tr>
                    <td valign="top" class="mcnTextContent" width="600" style="padding: 9px 0px 9px 0px;background-color: #4ca036;mso-table-lspace: 0pt;mso-table-rspace:0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;font-family: Helvetica;font-size: 11px;line-height: 125%;text-align:center;">
                      <img align="center" alt="" src="http://greencode.co/images/logo_email_nuevo.png" width="233" style="max-width: 233px;padding-bottom: 0;display: inline !important;vertical-align: bottom;border: 0;outline: none;text-decoration:none;-ms-interpolation-mode: bicubic;" class="mcnImage">
                    </td>
                  </tr>
                  </tbody>
                </table>
              </td>
            </tr>
            </tbody>
          </table>
        </td>
      </tr>
      </tbody>
    </table>
    <!-- // END PREHEADER -->
  </td>
</tr>

<tr style="background-color:#ffffff;">
  <td align="center" valign="top" style="mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;background-color:#ffffff;">
    <table border="0" cellpadding="0" cellspacing="0" width="100%" id="templateColumns" style="border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;border-top: 0;border-bottom: 0;background-color:#ffffff;">
      <tbody>
      <tr>
        <td align="left" valign="top" class="columnsContainer" width="100%" style="mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">
          <table border="0" cellpadding="0" cellspacing="0" width="100%" class="templateColumn" style="border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;width: 100%;">
            <tbody>
            <tr>
              <td valign="top" class="leftColumnContainer" style="mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust:100%;">
                <table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnCaptionBlock" style="border-collapse:collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">
                  <tbody class="mcnCaptionBlockOuter">
                  <tr>
                    <td class="mcnCaptionBlockInner" valign="top" style="padding: 9px;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">
                      <table border="0" cellpadding="0" cellspacing="0" class="mcnCaptionRightContentOuter" width="100%" style="border-collapse:collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">
                        <tbody>
                        <tr>
                          <td valign="top" class="mcnCaptionRightContentInner" style="padding: 0 9px;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">
                            <table class="mcnCaptionRightTextContentContainer" align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">
                              <tbody>
                              <tr>
                                <td valign="top" class="mcnTextContent" style="mso-table-lspace:7pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #858585;font-family: Helvetica;font-size:15px;line-height: 150%;text-align: left;padding: 50px 0px;">
                                  <p style="padding: 0px 0px;text-align: left;mso-table-lspace:0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;font-family: Helvetica;font-size:15px;line-height: 150%;">
                                    En giftcode queremos que nunca olvides las fechas especiales de tus amigos y que siempre tomes la mejor decision al momento de dar un regalo.
                                  </p>
                                  <p style="padding: 0px 0px;text-align: left;mso-table-lspace:0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;font-family: Helvetica;font-size:15px;line-height: 150%;">
                                    <%= ( @friends.length > 1 ) ? "Tus amigos #{ @friends.to_sentence(locale: GlobalConstants.I18n_locale ) } se han"  : ('Tu amigo ' + @friends[0]+' se ha ' ) %> unido a giftcode, ya puedes saber sus marcas favoritas y sus fechas especiales.
                                  </p>
                                  <p style="padding: 25px 0px">
                                    <a href="<%= friends_url %>" target="_blank" style="text-decoration: none;background-color: #4ca036;color: #fff;font-family: Helvetica;font-size:15px;line-height: 150%;-webkit-border-radius: 3px;border-radius: 3px;padding: 10px;display: block;width: 95px;margin: 0 auto;"><strong>Entérate aquí</strong></a>
                                  </p>
                                  <p style="padding: 0px 0px;text-align: left;mso-table-lspace:0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;font-family: Helvetica;font-size:15px;line-height: 150%;">
                                    Queremos que vayas a la fija.
                                  </p>
                                  <p style="padding: 0px 0px;text-align: left;mso-table-lspace:0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;font-family: Helvetica;font-size:15px;line-height: 150%;">
                                    Seguiremos en contacto.
                                  </p>
                                  <%= render 'firma' %>
                                </td>
                              </tr>
                              </tbody>
                            </table>
                          </td>
                        </tr>
                        </tbody>
                      </table>
                    </td>
                  </tr>
                  </tbody>
                </table>
              </td>
            </tr>
            </tbody>
          </table>
        </td>
      </tr>
      </tbody>
    </table>
  </td>
</tr>

<%= render 'footer_gift_code' %>

</tbody>
</table>
<!-- // END TEMPLATE-->
</td>
</tr>
</tbody>
</table>
</center>
<%= render "footer" %>