config/routes.rb
Greencode::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  post '/office_admin' => 'office_admin/dashboard#index', :as => :office_admin_root

  root :to => 'pages#home'

  devise_for :users,
             :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" },
             :skip => [ :password, :registration ]

  match '/delayed_job' => DelayedJobWeb, :anchor => false

  get '/gracias' => 'pages#gracias'
  get '/fbshared' => 'pages#fbshared'
  get '/fbshared2' => 'pages#fbshared2'
  get '/fbshared3' => 'pages#fbshared3'
  match 'sitemap.xml.gz', :controller => 'sitemap', :action => 'index'

    match '/como-funciona' => 'pages#how_it_works', :as => :how_it_works_pages

    match '/eco-amigable' => 'pages#projects', :as => :ecoamigable_pages
    match '/retailers' => 'pages#customers', :as => :customers_pages
    match '/retailers_beneficios' => 'pages#customers2', :as => :customers2_pages
    match '/terminos-y-condiciones' => 'pages#tos', :as => :tos_pages
    match '/politicas-de-privacidad' => 'pages#politica', :as => :politica_pages
    match '/terminos-y-condiciones-concurso' => 'pages#concurso', :as => :tycc_pages
    match '/concurso2014' => 'pages#concurso2014', :as => :tycc2014_pages

    match '/contacto' => 'contacts#create', :via => :post , :as => :contacts

    match '/mis-marcas-favoritas' => 'favorites#index', :via => :get , :as => :favorites
    match '/selecciona-tus-marcas-favoritas' => 'favorites#index', :via => :get , :as => :favorites_first_time
    match '/confirma-tus-datos' => 'settings#edit', :via => :get , :as => :first_time
    match '/mi-marca-favorita/:brand_id/actualizar' => 'favorites#add', :via => :put , :as => ''
    match '/compartir-en-facebook'  => 'favorites#facebook_wall', :via => :post, :as => ''

    match '/bonos-recibidos' => 'gift_codes#index_angular', :via => :get, :as => :gift_codes
    match '/bonos-enviados' => 'gift_codes#index_sent_angular', :via => :get, :as => :gift_codes_sent
    match '/bono/:view_id/token/:token' => 'gift_codes#show', :via => :get, :as => :gift_code
    match '/bono/crear' => 'gift_codes#create', :via => :post, :as => :gift_code_create
    match '/bono/:ref_sale' => 'gift_codes#download', :via => :get, :as => :gift_code_download
    match '/bono/:ref_sale/view' => 'gift_codes#view', :via => :get, :as => :gift_code_view

    match '/perfil' => 'settings#edit', :via => :get, :as => :edit_settings
    match '/perfil' => 'settings#update', :via => :put, :as => :settings
    match '/perfil/validar_correo/:token' => 'settings#validate_account', :via => :get, :as => :validate_account_settings
    match '/confirmation_email' => 'settings#confirmation_email', :via => :put
    match '/confirmation_birthday' => 'settings#confirmation_birthday', :via => :put
    match '/confirmation_city' => 'settings#confirmation_city', :via => :put

    match '/regalar-bono' => 'give#index_brands_angular', :via => :get, :as => :give
    match '/regalar-bono-amigo' => 'give#index_friends_angular', :via => :get, :as => :friend_give

=begin
    match '/puntos' => 'points#index', :via => :get, :as => :points
    match '/puntos/giftcode/:ref_sale' => 'points#gift_code', :via => :get, :as => :gift_codes_points
    match '/services/points/campaigns' => 'points#json_campaigns_points', :via => :get, :as => :services_points
    match '/services/points/campaigns/:campaign_id/gift_codes/create' => 'points#create_gift_code', :via => :post, :as => :services_points_create_gift_code
=end

=begin
    match '/amigos' => 'friends#index_angular', :via => :get, :as => :friends
    match '/invitar-amigo/:fbk_user_id' => 'friends#invite', :via => :post, :as => :invite_friend
    match '/perfil/amigo/:user_id' => 'friends#profile', :via => :get, :as => :profile_friend
    match '/amigos/referidos' => 'friends#referrals', :via => :get, :as => :services_friends_referrals
    match '/amigos/invitados' => 'friends#guests', :via => :get, :as => :services_friends_guests
    match '/amigos/por-invitar' => 'friends#for_inviting', :via => :get, :as => :services_friends_for_inviting
    match '/amigos/en-giftcode' => 'friends#in_gift_code', :via => :get, :as => :services_friends_in_gift_code
=end

    match '/json/amigos' => 'json#friends', :via => :get, :as => :friends_json
    match '/json/referidos-amigos' => 'json#referrals_friends', :via => :get, :as => :referrals_friends_json
    match '/amigos/referidos' => 'friends#referrals', :via => :get, :as => :services_friends_referrals
    match '/json/parametros-marca-giftcode' => 'json#brand_parameters_gift_code',  :via => :post, :as => :brand_parameters_gift_code_json
    match '/json/marcas' => 'json#brands',  :via => :get, :as => :brands_json
    match '/json/marcas-favoritas-amigo-regalar' => 'json#brands_favorites_friend_give',  :via => :post, :as => :brands_favorites_friend_give_json
    match '/json/marcas-favoritas' => 'json#favorites',  :via => :get, :as => :brand_favorites_json
    match '/json/marcas-favoritas-amigo/:friend_id' => 'json#favorites_friend',  :via => :get, :as => :brand_favorites_friend_json
    match '/json/marcas-favoritas-amigos' => 'json#friends_favorite_brands',  :via => :get, :as => :friends_favorite_brands_json
    match '/json/marca-favoritas-amigos/:brand_id' => 'json#friends_favorite_brand',  :via => :get, :as => :friends_favorite_brand_json
    match '/json/invite-amigos' => 'json#invite_friends', :via => :get, :as => :invite_friend_json
    match '/json/gift_code' => 'json#gift_code', :via => :post, :as => :gift_code_json
    match '/json/gift_code_sent' => 'json#gift_code_sent', :via => :post, :as => :gift_code_sent_json
    match '/json/gift_codes' => 'json#gift_codes', :via => :get, :as => :gift_codes_json
    match '/json/gift_codes_sent' => 'json#gift_codes_sent', :via => :get, :as => :gift_codes_sent_json
    match '/json/date_time_server' => 'json#get_date_time_server', :via => :get, :as => :get_date_time_server_json

    match '/payments/:ref_sale' => 'payments#index', :via => :get, :as => :payments
    match '/payments/:ref_sale' => 'payments#index', :via => :put, :as => :payments
    match '/payments/confirmation/:ref_sale' => 'payments#confirmation', :via => :get, :as => :confirmation_payments
    match '/payments/demo/:ref_sale' => 'payments#demo', :via => :get, :as => :demo_payments

  match '/favorites/suggest' => 'favorites#suggest', :via => :post

  match '/redemption' => 'third_party#redemption', :via => :post
  match '/reverse_redemption' => 'third_party#reverse_redemption', :via => :post
  match '/pending_redemption' => 'third_party#pending_redemption', :via => :post
  match '/confirm_redemption' => 'third_party#confirm_redemption', :via => :post
  match '/get_balance' => 'third_party#get_balance', :via => :post
  match '/embebed_giftcode' => 'third_party#embebed_giftcode', :via => :get, :as => :embebed_giftcode
  match '/embebed_giftcode_create' => 'third_party#embebed_giftcode_create', :via => :post, :as => :embebed_giftcode_create
  match '/embebed_giftcode_confirmation' => 'third_party#embebed_giftcode_confirmation', :via => :get, :as => :embebed_giftcode_create
  match '/get_payments' => 'third_party#get_brand_payments', :via => :post

  get '/bonos_gratuitos' => 'gift_code_free#index'

  get '/nosotros' => 'pages#team'
  get '/landing_2' => 'pages#landing2'
  get '/landing_3' => 'pages#landing_3'
  get '/landing_4' => 'pages#landing_4'
  match '/:brand_name' => 'landing_page#index', :via => :get, :as => :landing_page

  use_doorkeeper

  namespace :api do
    namespace :v1 do
      resource  :settings do
        collection do
          get :profile
          put :update_image
          put :update_birthday
          put :update
          get :birthday_confirmation
        end
      end
      resources :categories, :only => [:index]
      resources :friends, :only => [:index, :friends_in_gift_code]
      resource :brands, :only => [] do
        collection do
          get :all
          get 'friends_favorite_brand/:brand_id', to: :friends_favorite_brand
          get :favorite_brands
        end
      end
      resource :gift_codes, :only => [] do
        collection do
          get :sent
          get :received
          get 'received/:ref_sale', to: :gift_code_received
          post :create
          get 'parameters_brand/:brand_id', to: :parameters_brand
        end
      end
      resource :favorites, :only => [] do
        collection do
          post :add
        end
      end

    end
  end

  namespace :api do
    namespace :off do
      namespace :v1 do
        resources :pages,  :only => [:index] do
          collection do
            get :':brand_name', to: :index
          end
        end
        resources :brands, :only => [:index, :show]
        resources :gift_codes, :only => [:create]
      end
    end
  end

end

app/controllers/payments_controller.rb
# encoding: UTF-8
require 'rest-client'

class PaymentsController < ApplicationWebController

  def index
    @payment =  Payments.new( params )
    if @payment.start request
      render :layout => @payment.type
    else
      render :layout => @payment.type, :action => 'error'
    end
  end

  def confirmation
    @payment =  Payments.new( params )
    if @payment.finalize
      render :layout => @payment.type
    else
      render :layout => @payment.type, :action => 'error'
    end
  end


  def demo
    @payment =  Payments.new( params )
    if @payment.demo_finalize
      render :layout => @payment.type, :action => 'confirmation'
    else
      render :layout => @payment.type, :action => 'error'
    end
  end

end

app/helpers/payments_helper.rb
module PaymentsHelper

  def button_pay(gift_code)
    campaign = gift_code.gift_card.campaign
    @brand_codes = campaign.brand_codes.find_by_active_for_payment true
    bt = "No tiene medio de pago"
    if !@brand_codes.nil?
      case @brand_codes.third_party_entity.name.to_s
        when ThirdPartyEntity::ENTITY[:redeban]
          bt = redeban(gift_code)
      end
    end
    return bt
  end

  private
    def redeban(gift_code)
      if @brand_codes.terminal && @brand_codes.code && @brand_codes.type_terminal
        return "<a class='button pre continue' href='#{ payments_path(:ref_sale => gift_code.ref_sale)}'>Pagar</a>".html_safe
      else
        return "No se obtiene información de la campaña para la entidad"
      end
    end
end

app/views/payments/_billing_data_credibanco.html.erb
<i class="fi-info size-12"> Los datos deben coincidir con la tarjeta</i>
<br>
<br>
<div class="row" ng-class="{ error: form.names.$invalid  && form_payment_sending}" >
  <div class="small-5 columns"><label class="right inline">Nombres *</label></div>
  <div class="small-7 columns" >
    <input class="error" type="text" ng-model="payment.names" name="names" required autocomplete="off" >
    <small class="error" ng-if="form.names.$invalid  && form_payment_sending">
      <div ng-show="form.names.$error.required">Campo obligatorio.</div>
    </small>
  </div>
</div>

<div class="row" ng-class="{ error: form.last_names.$invalid  && form_payment_sending}" >
  <div class="small-5 columns"><label class="right inline">Apellidos *</label></div>
  <div class="small-7 columns" >
    <input class="error" type="text" ng-model="payment.last_names" name="last_names" required autocomplete="off" >
    <small class="error" ng-if="form.last_names.$invalid  && form_payment_sending">
      <div ng-show="form.last_names.$error.required">Campo obligatorio.</div>
    </small>
  </div>
</div>

<div class="row"  ng-class="{ error: form.gender.$invalid && form_payment_sending }">
  <div class="small-5 columns"><label class="right inline">Género *</label></div>
  <div class="small-7 columns">
    <select ng-model="payment.gender" name="gender"  required >
      <option value="" ></option>
      <option value="M" >Masculino</option>
      <option value="F" >Femenino</option>
    </select>
    <small class="error" ng-if="form.gender.$invalid && form_payment_sending ">
      <div ng-show="form.gender.$error.required">Campo obligatorio.</div>
    </small>
  </div>
</div>

<div class="row"  ng-class="{ error: form.nationality.$invalid && form_payment_sending }">
  <div class="small-5 columns"><label class="right inline">Nacionalidad *</label></div>
  <div class="small-7 columns" ng-init="countries=<%= countries_list.to_json %>">
    <select ng-model="payment.nationality" name="nationality"  required >
      <option value="" ></option>
      <option ng-repeat="country in countries | orderBy:'2'" value="{{country[0]}}" >{{country[2]}}</option>
    </select>
    <small class="error" ng-if="form.nationality.$invalid && form_payment_sending">
      <div ng-show="form.nationality.$error.required">Campo obligatorio.</div>
    </small>
  </div>
</div>

<div class="row"  ng-class="{ error: form.number_identifier.$invalid && form_payment_sending }">
  <div class="small-5 columns"><label class="right inline">Numero identificación *</label></div>
  <div class="small-7 columns" >
    <input class="error" type="text" ng-model="payment.number_identifier" name="number_identifier" isNumberCustom required autocomplete="off" >
    <small class="error" ng-if="form.number_identifier.$invalid  && form_payment_sending">
      <div ng-show="form.number_identifier.$error.required">Campo obligatorio.</div>
      <div ng-show="form.number_identifier.$error.isNumberCustom">Campo numerico.</div>
    </small>
  </div>
</div>


<div class="row">
  <div class="small-12 columns">
    <i class="right">Dirección de facturación</i>
  </div>
</div>
<br>
<div class="row" ng-class="{ error: form.address.$invalid  && form_payment_sending}" >
  <div class="small-5 columns"><label class="right inline">Dirección *</label></div>
  <div class="small-7 columns" >
    <input class="error" type="text" ng-model="payment.address" name="address" required autocomplete="off" >
    <small class="error" ng-if="form.address.$invalid  && form_payment_sending">
      <div ng-show="form.address.$error.required">Campo obligatorio.</div>
    </small>
  </div>
</div>

<div class="row"  ng-class="{ error: form.country.$invalid && form_payment_sending }">
  <div class="small-5 columns"><label class="right inline">País *</label></div>
  <div class="small-7 columns">
    <select ng-model="payment.country" name="country"  required >
      <option value="" ></option>
      <option ng-repeat="country in countries | orderBy:'2'" value="{{country[0]}}" >{{country[2]}}</option>
    </select>
    <small class="error" ng-if="form.country.$invalid && form_payment_sending ">
      <div ng-show="form.country.$error.required">Campo obligatorio.</div>
    </small>
  </div>
</div>

<div class="row" ng-class="{ error: form.state.$invalid  && form_payment_sending}" >
  <div class="small-5 columns"><label class="right inline">Departamento *</label></div>
  <div class="small-7 columns" >
    <input class="error" type="text" ng-model="payment.state" name="state" required autocomplete="off" >
    <small class="error" ng-if="form.state.$invalid  && form_payment_sending">
      <div ng-show="form.state.$error.required">Campo obligatorio.</div>
    </small>
  </div>
</div>

<div class="row" ng-class="{ error: form.city.$invalid  && form_payment_sending}" >
  <div class="small-5 columns"><label class="right inline">Ciudad *</label></div>
  <div class="small-7 columns" >
    <input class="error" type="text" ng-model="payment.city" name="city" required autocomplete="off" >
    <small class="error" ng-if="form.city.$invalid  && form_payment_sending">
      <div ng-show="form.city.$error.required">Campo obligatorio.</div>
    </small>
  </div>
</div>

<div class="row" ng-class="{ error: form.postal_code.$invalid  && form_payment_sending}" ng-show=" payment.country == 'US' || payment.country == 'CA' " >
  <div class="small-5 columns"><label class="right inline">Código postal *</label></div>
  <div class="small-7 columns" ng-init="payment.postal_code=''">
    <input class="error" type="text" ng-model="payment.postal_code" name="postal_code" ng-required=" payment.country == 'US' || payment.country == 'CA' " autocomplete="off" >
    <small class="error" ng-if="form.postal_code.$invalid  && form_payment_sending">
      <div ng-show="form.postal_code.$error.required">Campo obligatorio.</div>
    </small>
  </div>
</div>

<div class="row" ng-class="{ error: form.phone.$invalid  && form_payment_sending}" >
  <div class="small-5 columns"><label class="right inline">Telefono *</label></div>
  <div class="small-7 columns" >
    <input class="error" type="text" ng-model="payment.phone" name="phone" required autocomplete="off" >
    <small class="error" ng-if="form.phone.$invalid  && form_payment_sending">
      <div ng-show="form.phone.$error.required">Campo obligatorio.</div>
    </small>
  </div>
</div>

<div class="row" ng-class="{ error: form.cell.$invalid  && form_payment_sending}" >
  <div class="small-5 columns"><label class="right inline">Celular *</label></div>
  <div class="small-7 columns" >
    <input class="error" type="text" ng-model="payment.cell" name="cell" required autocomplete="off" >
    <small class="error" ng-if="form.cell.$invalid  && form_payment_sending">
      <div ng-show="form.cell.$error.required">Campo obligatorio.</div>
    </small>
  </div>
</div>


<div class="row" ng-class="{ error: form.email.$invalid  && form_payment_sending }" >
  <div class="small-5 columns"><label class="right inline">Correo *</label></div>
  <div class="small-7 columns" >
    <input class="error" type="email" ng-model="payment.email" name="email" required ng-pattern="EMAIL_REGEXP" autocomplete="off" >
    <small class="error" ng-if="form.email.$invalid  && form_payment_sending">
      <div ng-show="form.email.$error.required">Campo obligatorio.</div>
      <div ng-show="form.email.$error.pattern">Ingresar un correo electronico valido.</div>
    </small>
  </div>
</div>

app/views/payments/_confirmation_default.html.erb
<div class="row">
  <% unless @payment.payment_rejected  %>
  <div class="bono confirmation-payment <%= ( @payment.type == 'application' ) ? 'bigone' : 'bigone_wl' %> centered" >
    <div class="row">
      <div class="large-4-static columns">
        <img ng-src="<%= @payment.gift_code.gift_card.campaign.brand.image_url(:thumb180) %>" class="brand-ico" width="180" height="181" alt="Logo Fold">
      </div>
      <div class="large-8-static columns">
        <div class="whos">
          <h4><span class="greentxt">De: </span><%= truncate(@payment.gift_code.from_name_capitalize, length: 27)%></h4>
          <h4><span class="greentxt">Para: </span><%= truncate(@payment.gift_code.to_name_capitalize, length: 27) %></h4>
          <h2><%= @payment.gift_code.gift_card.cost_current %></h2>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="large-10 columns large-centered">
        <div class="giftnote">
          <p class="in-modal"><%= @payment.gift_code.body_message %></p>
        </div>
      </div>
    </div>
  </div> <!-- /bono -->
  <br />
  <div class="bono confirmation-payment <%= ( @payment.type == 'application' ) ? 'white' : 'whitelabel' %> flipped centered">
    <div class="row">
      <div class="whos">
        <img src="/assets/icono_grande.png" class="qr" alt="" width="74" height="84" />
        <h6 class="subheader text-center">&nbsp;</h6>
        <!--<h6 class="subheader text-center">Ciudad de destino: <%#  @payment.gift_code.to_city.name %></h6>-->
        <h6 class="subheader text-center">Válido hasta: <%= l @payment.gift_code.valid_until, :format => :web, :locale => :es %></h6>
      </div>
    </div>
    <div class="greenbg">
      <div class="row">
        <div class="large-10 columns large-centered">
          <p class="legal-advice whitetxt">Con este bono electrónico, estas contribuyendo con el medio ambiente al evitar el uso de tarjetas plásticas</p>
        </div>
      </div>
    </div>
  </div><!-- /bono white -->
  <% end  %>
</div><!-- /row -->

app/views/payments/_gateway_credibanco.html.erb
<!--<div class="row text-justify" >-->
  <!--<div class="large-12 columns">-->
    <!--<div class="brands shopping" >-->

      <div class="shop" ng-controller="CredibancoGatewayCtrl" >

        <div class="row">
          <div class="large-12 columns" ng-init="next=false">
            <div class="row">
             <div class="large-12 columns" ng-hide="next">
                <h2 class="whitetxt subheader centered">Revisa todos los datos</h2>
                <br><br>
                <div class="large-3 columns">&nbsp;</div>
                 <div class="large-6 columns">
                     <div class="row">
                        <div class="small-1 columns">&nbsp;</div>
                        <div class="small-3 columns"><i class="fi-mail"> e-Mail</i>:</div>
                        <div class="small-7 columns " ><label class="right whitetxt ng-binding" ng-bind="gift_code.to_email" ></label> </div>
                        <div class="small-1 columns"></div>
                     </div>
                     <div class="row" ng-show="gift_code.to_mobile_phone" >
                       <div class="small-1 columns">&nbsp;</div>
                       <div class="small-3 columns"><i class="fi-telephone"> Celular</i>:</div>
                       <div class="small-7 columns" ><label class="right whitetxt ng-binding" ng-bind="gift_code.to_mobile_phone"></label> </div>
                       <div class="small-1 columns"></div>
                     </div>
                     <div class="bono sent-received">
                       <div class="row collapse large-12">
                         <div class="large-4-static columns">
                           <img ng-src="{{images_brand.image.thumb180.url}}" class="brand-ico smallish" />
                         </div>
                         <div class="large-8-static columns">
                           <div class="whos">
                             <h4><span class="greentxt">De: </span> {{gift_code.from_first_name + ' ' + gift_code.from_last_name}} </h4>
                             <h4><span class="greentxt">Para: </span> {{gift_code.to_first_name + ' ' + gift_code.to_last_name}} </h4>
                             <h2  ng-bind="gift_code.currency_short_name + ' ' + gift_code.cost_current" ></h2>
                           </div>
                         </div>
                       </div>
                       <div class="row">
                         <div class="large-10 columns large-centered">
                           <div class="giftnote">
                             <p class="in-modal" ng-bind="gift_code.body_message"></p>
                           </div>
                         </div>
                       </div>
                     </div>
                     <div class="row">
                       <div class="small-1 columns">&nbsp;</div>
                       <div class="small-3 columns"><i class="fi-cloud"> Servicio</i>:</div>
                       <div class="small-7 columns"><label class="right whitetxt ng-binding"  ng-bind="cost.admin.currency.short_name + ' ' + cost.admin.value" ></label> </div>
                       <div class="small-1 columns"></div>
                     </div>
                     <div class="row">
                       <div class="small-1 columns">&nbsp;</div>
                       <div class="small-3 columns"><i class="fi-dollar-bill"> Total</i>:</div>
                       <div class="small-7 columns"><label class="right whitetxt ng-binding"  ng-bind="gift_code.total_current"></label> </div>
                       <div class="small-1 columns"></div>
                     </div>
                     <div class="row centered">
                        <br>
                        <a class="button gray pre radius" ng-click="close(true)">Atrás</a>
                        <a class="" ng-click="next = true"><%= image_tag('boton_credibanco.png') %></a>
                     </div>
                </div>
               <div class="large-3 columns">&nbsp;</div>

             </div>

             <div class="large-12 columns" ng-show="next"   >
               <h2 class="whitetxt subheader centered">Ingrese información del pago</h2>
               <br>
               <form name="form" ng-submit="payment_sent(form, payment)" novalidate ng-init="ref_sale='<%= params[:ref_sale] %>';" >
                 <hr class="no-margin">
                 <div class="large-6 columns">
                   <%= render 'payments/billing_data_credibanco' %>
                 </div>
                 <div class="large-6 columns" >
                   <%= render 'payments/card_data_credibanco' %>
                 </div>
               </form>
               <div ng-if="preload==true" class="preloader"></div>
             </div>
            </div>
          </div>
        </div>
      </div>
      <div ng-if="_data==false" class="preloader"></div>
    <!--</div>-->
  <!--</div>-->
<!--</div>-->
<% if Rails.env.production? %>
    <%= javascript_include_tag 'generateDFP-1.0PROD' %>
<% else %>
    <%= javascript_include_tag 'generateDFP-1.0TEST' %>
<% end %>

app/views/payments/_request_credibanco.html.erb
<%= @payment.message %>

app/views/payments/_request_redeban.html.erb
<div class="row">
  <object
  type="text/html"
  data="<%= "#{@payment.setup[:web]}?idTerminal=#{@payment.data['cabeceraRespuesta']['infoPuntoInteraccion']['idTerminal']}&idTransaccion=#{@payment.data['infoTransaccionResp']['idTransaccionActual']}" %>"
  style="width: 100%; height:750px;" >
    ERROR ( No se logro cargar ambiente de pago. )
  </object>
</div>
<script>
    var eventMethod = window.addEventListener ? "addEventListener" : "attachEvent";
    var eventer = window[eventMethod];
    var messageEvent = eventMethod == "attachEvent" ? "onmessage" : "message";
    eventer(messageEvent,function(e) {
        switch(e.data){
            case 'Cancelacion':
                console.log('Cancelación');
                <% if session[:callback].present? %>
                    window.location = "<%= session[:callback] %>";
                <% else %>
                    window.location = "<%= root_path %>";
                <% end %>
                break;
            case 'Error':
                console.log('Error');
                break;
            case 'Finalizacion':
                console.log('Finalización');
                <% if session[:callback].present? %>
                    window.location = "<%= session[:callback] %>";
                <% else %>
                    window.location = "<%= confirmation_payments_path(:ref_sale => @payment.gift_code.ref_sale) %>";
                <% end %>
                break;
            default:
                console.log(e.data);
                break;
        }
    },false);
</script>

app/views/payments/confirmation.html.erb
<% if @payment.gift_code.gift_code_state_id == GiftCodeState::STATES[:payment_rejected] || @payment.gift_code.gift_code_state_id ==  GiftCodeState::STATES[:generated_external_web_payment_rejected]  %>
    <% if @payment.type == 'application' %>
        <br>
        <br>
        <br>
    <% end %>
    <div class="row">
      <div class="large-10 columns large-centered">
        <div class="alert-box warning text-center radius">Pago rechazado</div>
      </div>
    </div>
<% else %>
    <%if @payment.gift_code.send_notifications_now %>
        <% if @payment.type == 'application' %>
        <br>
        <br>
        <br>
        <div class="row">
          <div class="large-10 columns large-centered">
            <!--alert-box success radius-->
            <div class="text-center alert-box greentxt radius"><i>Hola, Tu Giftcode para <strong><%= @payment.gift_code.to_name_capitalize %></strong> ha sido enviado exitosamente!</i></div>
          </div>
        </div>
        <% else %>
        <div class="row">
          <div class="large-10 columns large-centered">
            <div class="alert-box success text-center radius">Hola, el bono de regalo para <strong><%= @payment.gift_code.to_name_capitalize %></strong> ha sido enviado exitosamente!</div>
          </div>
        </div>
        <% end %>
    <% end %>
<% end %>
<%=
    case @payment.entity.name
      when ThirdPartyEntity::ENTITY[:credibanco]
        if @payment.demo
          render 'payments/confirmation_default'
        else
          render 'payments/confirmation_credibanco'
        end
      else
        render 'payments/confirmation_default'
    end
%>
<% if @payment.type == 'application' %>
<div class="row padding-50">
  <div class="large-12 text-center columns">
    <%= link_to '<span class="gifty"></span><span class="border">Continuar</span>'.html_safe, gift_codes_sent_path, class: 'button success radius normal text-center'  %>
  </div>
</div>
<% end %>